/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Lamp(props) {
  const { nodes, materials } = useGLTF('/tablelamp.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Standing_lamp_01_Circle003-Mesh'].geometry}
        material={materials['795548']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Standing_lamp_01_Circle003-Mesh_1'].geometry}
        material={materials.DD9944}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Standing_lamp_01_Circle003-Mesh_2'].geometry}
        material={materials['455A64']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Standing_lamp_01_Circle003-Mesh_3'].geometry}
        material={materials.FFEB3B}
      />
    </group>
  )
}

useGLTF.preload('/tablelamp.glb')
