/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function IngLogo(props) {
  const { nodes, materials } = useGLTF('/models/Ing (1).glb')
  return (
    <group {...props} dispose={null}>
      <group
    
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[4.138, 3.996, 3.996]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials.Material}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Ing (1).glb')
