/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TransformControls } from '@react-three/drei'

export default function CharacterModel(props) {
  const { nodes, materials } = useGLTF('/characterModel.glb')
  const charcterref=useRef()
  return (
    <>
    {/* <TransformControls  object={charcterref.current}/> */}
      <group ref={charcterref} {...props} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.002']}
        position={[-0.001, 1.288, 0.106]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.024, 0.02, 0.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.003']}
        position={[-0.001, 1.291, 0.111]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.048, 0.003, 0.021]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-0.054, 1.289, 0.109]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.003, 0.002, 0.006]}
      />
      <group scale={0.677}>
        <primitive object={nodes.spine} />
        <skinnedMesh
          geometry={nodes.Cube001_Material001_0.geometry}
          material={materials['Material.001']}
          skeleton={nodes.Cube001_Material001_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube001_Material001_0_1.geometry}
          material={materials['Material.004']}
          skeleton={nodes.Cube001_Material001_0_1.skeleton}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0.058, 1.275, 0.033]}
        rotation={[0, 0.628, 0]}
        scale={[0.013, 0.013, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0.055, 1.291, 0.071]}
        rotation={[0, 1.493, 0]}
        scale={[0.039, 0.002, 0.001]}
      />
    </group>
    </>
  
  )
}

useGLTF.preload('/characterModel.glb')
