/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export default function CharacterModel(props) {
  const group = useRef()
  const {scene, animations } = useGLTF('/human (3).glb')
  const { actions } = useAnimations(animations, group)

  
  useEffect(()=>{
    // const sitting=actions[animations[0].name]
    // const tv=actions[animations[1].name]
    
    // if(doorOpen &&enterDoor){
    //     doorOpen.play()
    //     tv.play()
    // }
    // else{
    //   doorOpen.stop()
    // }

    if (actions['Action.002']) {
      actions['Action.002'].play();
    } else {
      console.warn("Action.002 not found in actions");
    }
    console.log("actions",actions)
    
      },[])



  return (
    <group ref={group} {...props} dispose={null}>
   <primitive object={scene}/>
    </group>
  )
}

useGLTF.preload('/human (3).glb')
