/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { TransformControls } from '@react-three/drei'


export default function SmartDustbin(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/smartDustbinRemake (1).glb')
  const { actions } = useAnimations(animations, group)
  const dustbin=useRef()
  useEffect(()=>{
    const dustbinOpen=actions[animations[0].name]

    
    if(dustbinOpen ){
      dustbinOpen.play()
    }
    else{
      dustbinOpen.stop()
    }
    
      },[props.enterProject1])
  useFrame(()=>{
console.log("dusbin",actions)

  })
  return (
    <>
    {/* <TransformControls object={group} /> */}
      <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.004']}
          position={[1.007, 1.74, 0.698]}
          rotation={[1.684, 0, 0]}
          scale={[0.296, 0.089, 0.089]}
        />
        <group
          name="Cylinder"
          position={[0.867, 1.734, 0.717]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.075}>
          <mesh
            name="Cylinder_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Cylinder_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          name="Cylinder001"
          position={[1.176, 1.734, 0.717]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.075}>
          <mesh
            name="Cylinder001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Cylinder001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_2.geometry}
            material={materials['Material.003']}
          />
        </group>
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['Material.006']}
          position={[1.018, 0.961, -0.245]}
          scale={[1, 1.302, 1]}
        />
        <mesh
          name="Plane001"
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials['Material.007']}
          position={[1.025, 2.46, -0.232]}
          rotation={[0.206, 0, 0]}
          scale={[0.953, 0.954, 0.953]}
        />
        <mesh
          name="Plane002"
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials['Material.008']}
          position={[1.032, 2.513, -0.306]}
          rotation={[0.219, 0, 0]}
          scale={[0.687, 0.687, 0.6]}
        />
      </group>
    </group>
    </>
  
  )
}

useGLTF.preload('/smartDustbinRemake (1).glb')
