/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function OnlyTv(props) {
  const { nodes, materials } = useGLTF('/Tv.glb')
  return (
    <group {...props}  dispose={null}>


      <group
       
       
        scale={[9.198, 5.984, 7.771]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_1.geometry}
          material={materials['Material.002']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Tv.glb')
