/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SelfDriving(props) {
  const { nodes, materials } = useGLTF('/models/selfDriving (1).glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.909, 0.472, 1.293]} rotation={[-Math.PI / 2, 0, 0]} scale={24.884}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['0.000000_0.000000_1.000000_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['0.000000_1.000000_1.000000_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['1.000000_1.000000_1.000000_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['1.000000_1.000000_1.000000_0.000000_0.000000']}
        />
      </group>
      <group position={[2.797, 0.472, -1.678]} rotation={[-Math.PI / 2, 0, 0]} scale={24.884}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2001.geometry}
          material={materials['0.000000_0.000000_1.000000_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3001.geometry}
          material={materials['0.000000_1.000000_1.000000_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4001.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5001.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6001.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7001.geometry}
          material={materials['1.000000_1.000000_1.000000_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8001.geometry}
          material={materials['1.000000_1.000000_1.000000_0.000000_0.000000']}
        />
      </group>
      <group position={[-0.046, 0.472, 1.076]} rotation={[-Math.PI / 2, 0, 0]} scale={17.9}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2002.geometry}
          material={materials['0.000000_0.000000_1.000000_0.000000_0.000000']}
          position={[-0.016, -0.013, 0]}
          scale={1.39}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3002.geometry}
          material={materials['0.000000_1.000000_1.000000_0.000000_0.000000']}
          position={[-0.016, -0.013, 0]}
          scale={1.39}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4002.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
          position={[-0.016, -0.013, 0]}
          scale={1.39}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5002.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
          position={[-0.016, -0.013, 0]}
          scale={1.39}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6002.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7002.geometry}
          material={materials['1.000000_1.000000_1.000000_0.000000_0.000000']}
          position={[-0.016, -0.013, 0]}
          scale={1.39}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8002.geometry}
          material={materials['1.000000_1.000000_1.000000_0.000000_0.000000']}
          position={[-0.016, -0.013, 0]}
          scale={1.39}
        />
      </group>
      <group position={[-0.104, 0.472, -1.461]} rotation={[-Math.PI / 2, 0, 0]} scale={21.951}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2003.geometry}
          material={materials['0.000000_0.000000_1.000000_0.000000_0.000000']}
          position={[0, 0.013, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3003.geometry}
          material={materials['0.000000_1.000000_1.000000_0.000000_0.000000']}
          position={[-0.007, 0.011, 0]}
          scale={1.134}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4003.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
          position={[-0.007, 0.011, 0]}
          scale={1.134}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5003.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
          position={[-0.007, 0.011, 0]}
          scale={1.134}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6003.geometry}
          material={materials['1.000000_0.690196_0.984314_0.000000_0.000000']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7003.geometry}
          material={materials['1.000000_1.000000_1.000000_0.000000_0.000000']}
          position={[-0.007, 0.011, 0]}
          scale={1.134}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8003.geometry}
          material={materials['1.000000_1.000000_1.000000_0.000000_0.000000']}
          position={[-0.007, 0.011, 0]}
          scale={1.134}
        />
      </group>
      <group position={[1.22, 1.422, -0.175]} scale={[2.139, 0.718, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials['Material.008']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.001']}
        position={[-0.262, 0.669, -0.989]}
        scale={[0.059, 0.182, 0.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.001']}
        position={[-0.262, 0.669, 0.513]}
        scale={[0.059, 0.182, 0.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.001']}
        position={[2.872, 0.669, 0.67]}
        scale={[0.059, 0.182, 0.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.001']}
        position={[2.877, 0.669, -0.898]}
        scale={[0.059, 0.182, 0.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material.001']}
        position={[-0.262, 0.48, -0.246]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.059, 1.176, 0.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material.001']}
        position={[2.889, 0.48, -0.138]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.059, 1.176, 0.059]}
      />
      <group position={[3.238, 2.143, 0.013]} rotation={[0, 0, -Math.PI / 2]} scale={0.104}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_2.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group position={[3.238, 2.143, -0.394]} rotation={[0, 0, -Math.PI / 2]} scale={0.104}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={materials['Material.007']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.004']}
        position={[0.667, 1.619, 0.832]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.216}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Material}
        position={[1.187, 2.307, -0.172]}
        scale={[2.057, 0.232, 0.949]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[1.179, 2.576, -0.186]}
        scale={[2.103, 0.1, 0.97]}
      />
    </group>
  )
}

useGLTF.preload('/models/selfDriving (1).glb')
