/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Table(props) {
  const { nodes, materials } = useGLTF('/newTable (1).glb')
  return (
    <group position={[1.015, 0.01, -0.081]} {...props} dispose={null}>
      <group  scale={[2.058, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[0.042, 0.523, 0.039]}
        scale={[2.392, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/newTable (1).glb')
