/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: The British Museum (https://sketchfab.com/britishmuseum)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/antinous-62886082c3b144d18ca516b396cf29f5
Title: Antinous
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Statue(props) {
  const { nodes, materials } = useGLTF('/statue1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[14.624, -0.935, 19.294]} rotation={[0, -0.214, -Math.PI / 2]} scale={0.176}>
        <group position={[-11.347, -22.627, -4.502]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_2.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_11.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.material_0}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/statue1.glb')
