/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Coffee(props) {
  const { nodes, materials } = useGLTF('/Espresso coffee.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials['13___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['09___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl003.geometry}
        material={materials['08___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl004.geometry}
        material={materials.Material__25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['09___Default']}
      />
    </group>
  )
}

useGLTF.preload('/Espresso coffee.glb')
