/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Projects(props) {
  const { nodes, materials } = useGLTF('/Passage.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow  
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials['Material.002']}
        position={[529.047, 21.63, -106.472]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[6.867, 9.297, 2.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials['Material.005']}
        position={[629.419, 24.096, -103.549]}
        scale={[2.147, 0.085, 9.715]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[522.212, 21.483, -102.952]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[4.574, 2.874, 2.684]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={nodes.Plane020.material}
        position={[629.358, 21.104, -102.952]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[4.574, 2.874, 2.681]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials['Material.004']}
        position={[548.416, 19.219, -111.546]}
        scale={[0.833, 0.238, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Material.004']}
        position={[550.038, 21.127, -111.805]}
        scale={[3.644, 2.18, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.004']}
        position={[503.19, 21.127, -111.805]}
        scale={[3.644, 2.18, 0.22]}
      />
    </group>
  )
}

useGLTF.preload('/Passage.glb')
