/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Projects(props) {
  const { nodes, materials } = useGLTF('/models/Passage (1) (1).glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials['Material.002']}
        position={[247.625, 142.8, -23.042]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[50.335, 95.424, 19.993]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[107.383, 141.675, 13.083]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[46.95, 21.069, 22.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials['Material.004']}
        position={[389.596, 125.552, -72.137]}
        scale={[6.107, 1.94, 3.462]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Material.004']}
        position={[401.484, 141.108, -81.086]}
        scale={[26.713, 17.782, 9.226]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.004']}
        position={[58.097, 141.108, -75.023]}
        scale={[26.713, 17.782, 2.993]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.006']}
        position={[610.588, 167.717, -37.05]}
        scale={[761.993, 0.607, 150.281]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[130.801, 162.997, 28.712]}
        scale={[15.435, 0.796, 228.975]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[1358.375, 141.675, 23.429]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[46.95, 21.069, 22.374]}
      />
    </group>
  )
}

useGLTF.preload('/models/Passage (1) (1).glb')
